#!/bin/bash -l
#
#SBATCH --job-name=test-run2
#SBATCH --output=%x.o%j
#SBATCH --error=%x.e%j
#SBATCH --time=12:00:00
#SBATCH --nodes=10
###SBATCH --nodelist bm-node001
#SBATCH --ntasks-per-node=16
#SBATCH --partition=batch2
#
# Partitions:
##SBATCH --partition=batch
##SBATCH --partition=batch2
##SBATCH --partition=fatbatch
##
## --job-name=runbatch  : name of the run
## --time=48:00:00      : walltime for the run
## --nodes=2            : number of nodes
## --ntasks-per-node=16 : number of processes per node
##
## --dependency=afterok:<jobid>
#
# NOTE: The value of 'ntasks-per-node' depends on the chosen queue.
#       You have to use the correct number of cores per node,
#       otherwise your job will be rejected by the batch system.
#
#   --ntasks-per-node=12   : on regular node (--partition=batch)
#   --ntasks-per-node=16   : on regular node (--partition=batch2)
#   --ntasks-per-node=28   : on fatnode (--partition=fatbatch)
#
#-----------------------------------------------------------------------

module load intel64/19.0up1
module load openmpi/intel/3.1.3-2019.1.144

cd ${SLURM_SUBMIT_DIR}

mpirun --bind-to core --report-bindings python3 montecarlo.py > monte_carlo_output

